
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./component/Header";
import AstroNote from "./component/AstroNote";
import Footer from "./component/Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AstroVoice",
  description: "Generated by Astro Nova Labs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white">
        <AstroNote/>   
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
